### ISSUE TITLE
Problem with KLF 200 in FHEM

### ISSUE THREAD

**Issue by Ro43** [buennerbernd/fhem#3]
I've installed FHEM on a loxberry system. After placing the both files in the right folder and restarting the FHEM Server i procced with the input

define Velux KLF200 192.168.x.xx

After pressing ENTER i get the response: Cannot load module KLF200

This I think is the relevant part of the logfile
2019.01.15 20:36:49 0: Excessively long <> operator at ./FHEM/83_KLF200.pm line 21. 2019.01.15 20:37:22 1: reload: Error:Modul 83_KLF200 deactivated: Excessively long <> operator at ./FHEM/83_KLF200.pm line 21. 2019.01.15 20:37:22 0: Excessively long <> operator at ./FHEM/83_KLF200.pm line 21.

I there any hint what could be the problem?

KR, Roman

**Comment by buennerbernd** [comment]
Hallo Roman,

diese Fehlermeldung deutet darauf hin, dass beim Download der Dateien von Github etwas schiefgegangen ist.
Hast du schon den vereinfachten Download über die update-Funktion probiert?
Es ist auf der Readme-Seite beschrieben:
https://github.com/buennerbernd/fhem/tree/master/KLF200/2.0
Diese Befehle müssen oben in die Kommandozeile im FHEM WebUI eingegeben werden.
Zwischen update und restart lass mal etwas Zeit vergehen, damit das commandref fertig generiert wird.
Dann steht dir unten in jedem Module über Link _Device specific help_ oder links über _Commandref_ eine nützliche Hilfe zur Verfügung.

Sollte der Fehler danach immernoch auftreten, dann schau mal auf deinem Dateisystem nach, ob die beiden Dateien
`/FHEM/83_KLF200.pm`
`/FHEM/83_KLF200Node.pm`
nach Perl-Code aussehen und poste mal deren Inhalt hier.

Ich hoffe, das bringt dich weiter.
Wenn du deine Geräte erfolgreich einrichten konntest, dann ruf mal bitte unter FHEM folgendes auf:
`fheminfo send`
Dadurch wird eine anonyme Statistik an FHEM geschickt und ich kann sehen, welche Geräte so verwendet werden und besseren Support leisten.

Gruß, Stefan.

**Comment by Ro43** [comment]
Hallo Stefan,

vielen Dank für deine rasche Unterstützung. Das war des Rätsels Lösung. Jetzt hab ich das Gerät angelegt. Jetzt geht es nur noch dran herauszufinden wie ich Befehle anlegen kann und diese dann idealerweise in Loxone integrieren kann.

Vielen Dank für deinen Support.

Roman

**Comment by buennerbernd** [comment]
Schön, dass es funktioniert hat.
Ich denke, mit Loxone musst du über MQTT kommunizieren.
https://fhem.de/commandref_DE.html#MQTT_GENERIC_BRIDGE
Da kann ich aber nicht weiterhelfen, hab ich noch nicht gemacht.
